### ISSUE TITLE
Option (or documentation) for preferring camelCase to underscore_words

### ISSUE THREAD

**Issue by ssokolow** [flintwork/pep8-naming#2]
I'd really like to extend my Travis CI stylistic consistency checks to also cover naming
but, for a variety of reasons (length, taste, etc.), I'm not willing to switch my codebases over
to underscore_words style for function and argument names.

How difficult would it be to extend (or document) pep8-naming so I can specify such a
preference in my `tox.ini` without having to maintain a fork of pep8-naming?

**Comment by sigmavirus24** [comment]
I tend to agree with @myint personally. This project isn't a generic way of enforcing naming style-guidelines with flake8, this is specifically to enforce pep8's naming guidelines, which it does (although sometimes too strictly). This should be a different plugin instead of being an extension of this plugin.
