### ISSUE TITLE
package naming

### ISSUE THREAD

**Issue by petrrr** [flintwork/pep8-naming#8]
I started to package this package for Macports but I find the naming confusing. This is a flake8 plugin, right?

So would a name starting like `flake8-naming` or `flake8-pep8-naming` be more appropriate. Of cause I could use different naming for MacPorts, but this probably only adds to the confusion ...

Any thoughts?

**Comment by sigmavirus24** [comment]
Hey @petrrr I'm surprised Florent didn't respond to this when they tagged it, but as I understand it, the name of the package was chosen because it enforces the naming guidelines in pep8. It's not only a flake8 extension, it still provides entry-points for the now deprecated flint project as well. Cheers!
